"Basic editor settings
set nocompatible            "disable vi compatibility
set backupdir=~/.vim/backup "directory for ~ files
set directory=~/.vim/swp    "directory for .swp files
set backspace=2             "enables normal backspace behavior
set backspace=indent,eol,start

"Enable vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"Set mapleader
let mapleader=","

"Let vundle manage vundle (required)
Plugin 'gmarik/Vundle.vim'

"Bundle 'tomasr/molokai'
Bundle 'morhetz/gruvbox'
Bundle 'jiangmiao/auto-pairs'
Plugin 'Valloric/YouCompleteMe'
Plugin 'nvie/vim-flake8'
Plugin 'vim-scripts/cctree'
Bundle 'tomasr/molokai'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'rhysd/vim-clang-format'

"Finish up vundle setup
call vundle#end()

"Filetype-specifics (note this HAS to be turned back on for vundle to work)
filetype plugin indent on

"YCM options
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_key_list_select_completion = ['<TAB>', '<Down>']
let g:ycm_key_list_previous_completion = ['<S-TAB>', '<Up>']
let g:ycm_global_ycm_extra_conf = '$HOME/.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_server_python_interpreter = '/usr/local/bin/python3'

"Do pyfmt
autocmd FileType python nnoremap <leader>y :0,$!yapf --style=facebook<CR>

""vim-clang-format options
let g:clang_format#detect_style_file = 1
let g:clang_format#auto_format = 1

"Colors
syntax on
set background=dark
set t_Co=256
let g:gruvbox_contrast_dark='hard'
colorscheme gruvbox

"Searching
set ignorecase  "searching: automatically ignore case
set smartcase   "searching: if searching for word with caps, disable ignorecase
set hlsearch
set incsearch

"Disable bell
set noerrorbells
set novisualbell
set t_vb=
autocmd! GUIEnter * set vb t_vb=

"Tab completion of filenames
set wildmode=longest,list,full  "search preferences for tab completion
set wildmenu            "enable tab completion

"Code settings
set foldmethod=indent   "automatic folding based on indentation
set foldignore=         "enable folding of '#' comments
set nofoldenable        "disable automatic folding on open. close fold with zc.
set number              "displays line numbers
nnoremap <space> za

"Tab behavior. Set to 4 spaces.
set shiftwidth=4
set expandtab
set tabstop=4
set softtabstop=4
set smarttab

"Ctags config
set tags=./tags;/

"Navigation
nnoremap j gj
nnoremap k gk

"Make copy/paste work in gvim/mvim
if has("gui_running")
  vmap <C-S-x> "+x
  vmap <C-S-c> "+y
  imap <C-S-v> <Esc>"+gP
endif

"Make splits a little more intuitive
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright
