"Basic editor settings
set nocompatible            "disable vi compatibility
set backupdir=~/.vim/backup "directory for ~ files
set directory=~/.vim/swp    "directory for .swp files
set backspace=2             "enables normal backspace behavior
set backspace=indent,eol,start
set paste                   "enables normal behavior of pasting

"Enable vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"Let vundle manage vundle (required)
Plugin 'gmarik/Vundle.vim'

"Rust syntax highlighting
Plugin 'wting/rust.vim'

"Colorschemes colorscheme
Bundle 'tomasr/molokai'
Bundle 'morhetz/gruvbox'
Bundle 'jordwalke/flatlandia'
Bundle 'chriskempson/vim-tomorrow-theme'
Bundle 'w0ng/vim-hybrid'
Bundle 'oguzbilgic/sexy-railscasts-theme'
Bundle 'ervandew/supertab'
Bundle 'jiangmiao/auto-pairs'
Bundle 'Valloric/YouCompleteMe'
Bundle 'rdnetto/YCM-Generator'
Bundle 'craigemery/vim-autotag'

"Finish up vundle setup
call vundle#end()

"vim-clang options
let g:clang_cpp_options = '-std=c++14 -stdlib=libc++'

"YCM options
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_collect_identifiers_from_comments_and_strings = 0
let g:ycm_confirm_extra_conf = 0
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_global_ycm_extra_conf = '$HOME/.ycm_global_ycm_extra_conf'
nnoremap <F11> :YcmForceCompileAndDiagnostics <CR>

"Filetype-specifics (note this HAS to be turned back on for vundle to work)
filetype plugin indent on

"Regex
set magic

"Colors
syntax on
set background=dark
set t_Co=256
colorscheme gruvbox

"Searching
set ignorecase  "searching: automatically ignore case
set smartcase   "searching: if searching for word with caps, disable ignorecase
set hlsearch

"Disable that goddamn bell
set noerrorbells
set novisualbell
set t_vb=
autocmd! GUIEnter * set vb t_vb=

"Tab completion of filenames
set wildmode=longest,list,full  "search preferences for tab completion
set wildmenu            "enable tab completion

"Code settings
set foldmethod=indent   "automatic folding based on indentation
set foldignore=         "enable folding of '#' comments
set nofoldenable        "disable automatic folding on open. close fold with zc.
set number              "displays line numbers

"Tab behavior. Set to 4 spaces.
set shiftwidth=4
set expandtab
set tabstop=4
set softtabstop=4
set smarttab

"Ctags config
set tags=./tags;/

"Make copy/paste work in gvim/mvim
if has("gui_running")
  vmap <C-S-x> "+x
  vmap <C-S-c> "+y
  imap <C-S-v> <Esc>"+gP
endif
